export enum RoutesEnum {
  ROOT = '/',
  LOGIN = '/login',
  DASHBOARD = '/dashboard',
  ROLES = '/roles',
  PERMISSIONS = '/permisos',
  PAISES = '/paises',
  DIVISIONES_GEOGRAFICAS = '/divisiones-geograficas',
  ALBERGUES = '/albergues',
  HABITACIONES = '/habitaciones',
  BENEFICIOS = '/beneficios',
  SERVICIOS = '/servicios',
  PERSONAS = '/personas',
  EXPEDIENTES = '/expedientes',
  RESIDENTES = '/residentes',
  RECIBOS = '/recibos',
  REPORTES = '/reportes',
  ENCARGADO = '/encargado',
  PROFILE = '/perfil',
}
